### ISSUE TITLE
nowritecb error thrown

### ISSUE THREAD

**Issue by scottcorgan** [rvagg/through2#1]
Any reason why I would be getting the following error:

```
uncaughtException no writecb in Transform class
Error: no writecb in Transform class
    at afterTransform (/Users/scott/www/particle/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:92:33)
    at TransformState.afterTransform (/Users/scott/www/particle/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:76:1
```

Code worked using `map-stream` module. Converterted to try this module and getting this error now.

Thanks.

**Comment by towry** [comment]
I had this error today and the reason is I called the `callback` more than once.

**Comment by dcousens** [comment]
Thanks @towry :+1:
