### ISSUE TITLE
Error: Cannot find module 'readable-stream/transform'

### ISSUE THREAD

**Issue by binarykitchen** [rvagg/through2#39]
Pretty self-explanatory:

```
$ gulp

Error: Cannot find module 'readable-stream/transform'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/videomail/staging/source/node_modules/gulp-util/node_modules/through2/through2.js:1:79)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

```
$ node -v
v0.10.36
```

And I spotted this during `npm install`

```
npm WARN unmet dependency /var/www/videomail/staging/source/node_modules/browserify/node_modules/deps-sort/node_modules/through2 requires readable-stream@'~1.0.17' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
```

Hmmm, what should I do?

**Comment by mafintosh** [comment]
what version of through2 are you using? also could you post the output `npm ls`?

**Comment by binarykitchen** [comment]
using version 0.6.3 here (as a dependency from the gulp-util package)

`npm ls` is way toooo huge to paste it here ... maybe i have network issues here and not everything is installed properly.

still using old npm here, maybe old npm cannot deal with network issues ...

```
$ npm -v
1.4.28
```

**Comment by binarykitchen** [comment]
forget this. dominic's npmd module is the answer to this problem. it was a network issue. all good now thanks to npmd.

**Comment by yarivat** [comment]
binarykitchen how did you resoved this issue i have the same error
node -v
v0.12.4

npm -v
2.10.1

**Comment by binarykitchen** [comment]
use `npmd` or just do

$ rm -rf node_modules
$ npm i

**Comment by a13632965388** [comment]
df
