### ISSUE TITLE
stream.push() after EOF?

### ISSUE THREAD

**Issue by VaJoy** [rvagg/through2#53]
hi I\`ve created a [gulp pulgin](https://github.com/VaJoy/gulp-embed) but it runs with some problems
here`s the codes of my plugin:
```javascript

'use strict';

var path = require('path');
var gutil = require('gulp-util');
var through2 = require('through2');
var PluginError = gutil.PluginError;
var ResourceEmbedder = require('./lib/resource-embedder2');

module.exports = function (options) {
    return through2.obj(function (file, enc, cb) {

        var filepath = file.path;

        //file not exsists
        if (file.isNull()) {
            this.emit('error', new PluginError('gulp-embed', 'File not found: "' + filepath + '"'));
            return cb();
        }

        var embedder = new ResourceEmbedder(filepath);

        embedder.get(function (markup) {
            var f = new gutil.File({
                cwd: '',
                path: path.basename(filepath),
                contents: new Buffer(markup)
            });

            this.push(f);
            cb();
        }.bind(this));

    })
};
```
it\`s weird that sometime it runs well but sometime it\`ll run with errors below:
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: stream.push() after EOF
  at readableAddChunk (D:\github\test\node_modules\gulp-embed\demo\node_modules\gulp-embed\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:184:15)
  at DestroyableTransform.Readable.push (D:\github\test\node_modules\gulp-embed\demo\node_modules\gulp-embed\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:162:10)
  at DestroyableTransform.Transform.push (D:\github\test\node_modules\gulp-embed\demo\node_modules\gulp-embed\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:133:32)
  at DestroyableTransform.<anonymous> (D:\github\test\node_modules\gulp-embed\demo\node_modules\gulp-embed\index.js:31:18)
  at doEmbedding (D:\github\test\node_modules\gulp-embed\demo\node_modules\gulp-embed\lib\resource-embedder2\src\resource-embedder.coffee:82:9)
  at process._tickCallback (node.js:355:11)
```
this problem seems to be that the stream is ending before I push the file? but I have no idea\`bout how it happened and how to solve it?

**Comment by VaJoy** [comment]
btw, the codes will run successfully almost every time if delay pushing file and invoking `cb`:
```javascript
        embedder.get(function (markup) {
            var f = new gutil.File({
                path: path.basename(filepath),
                contents: new Buffer(markup)
            });

            setTimeout(function(){  //delay
                this.push(f);
                cb();
            }.bind(this),3000)

        }.bind(this));
```

**Comment by VaJoy** [comment]
oh sorry it\`s bug from lib/resource-embedder2 and I`ve fixed it
